version: '3.9'

services:
  eureka:
    image: steeltoeoss/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      EUREKA_CLIENT_REGISTERWITH_EUREKA: "false"
      EUREKA_CLIENT_FETCHREGISTRY: "false"
      EUREKA_SERVER_ENABLESELFPRESERVATION: "false"
      SPRING_APPLICATION_NAME: "discovery-server"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
