version: '3.9'

services:
  eureka:
    image: steeltoeoss/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      EUREKA_CLIENT_REGISTERWITH_EUREKA: "false"
      EUREKA_CLIENT_FETCHREGISTRY: "false"
      EUREKA_SERVER_ENABLESELFPRESERVATION: "false"
      SPRING_APPLICATION_NAME: "discovery-server"
    networks:
      - app-network
    restart: always

  config-server:
    image: config-server
    container_name: config-server
    depends_on:
      - eureka
    ports:
      - "7090:7090"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_JWT_SECRET=${DB_JWT_SECRET}
      - DB_URL_USERS=${DB_URL_USERS}
#    volumes:
#      - ./common-config:/config-repo

    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge


